version: "3.3"

services:
# Some folks might not want to run via swarm
# In that case it fine to edit the base to use docker-compose
# Things you loose .. auto-update of secondary, the coolness of swarm mode
#  secondary:
#    image: cconstab/secondary
#    restart: unless-stopped
#    command: "-a ${ATSIGN} -p ${PORT} -s ${SECRET}"
#    ports:
#      - $PORT:$PORT
#    volumes:
#      - ~/atsign/etc/live/${DOMAIN}:/atsign/certs
#      - ~/atsign/etc/archive/${DOMAIN}:/archive/${DOMAIN}
#      - ~/atsign/${ATSIGN}:/atsign/storage

  cert:
    image: certbot/certbot
    volumes:
      - ~/atsign/etc:/etc/letsencrypt
      - ~/atsign/var:/var/lib/letsencrypt
      - ~/atsign/logs:/var/log/letsencrypt
    ports:
      - "80:8080"
    command:  certonly  --http-01-port 8080 --logs-dir /var/log/letsencrypt --standalone --domains ${DOMAIN} --non-interactive --agree-tos -m ${EMAIL}

  renew:
    image: certbot/certbot
    volumes:
      - ~/atsign/etc:/etc/letsencrypt
      - ~/atsign/var:/var/lib/letsencrypt
      - ~/atsign/logs:/var/log/letsencrypt
    ports:
      - "80:8080"
    command:  renew --http-01-port 8080
    #In case you want to force the issue (dry run first)
    #command:  renew --http-01-port 8080 --force-renew --dry-run

