version: "3.7"

services:
  renew:
    image: certbot/certbot
    volumes:
      - ~/atsign/etc:/etc/letsencrypt
      - ~/atsign/var:/var/lib/letsencrypt
      - ~/atsign/logs:/var/log/letsencrypt
    ports:
      - "80:8080"
    command:  renew --http-01-port 8080
    #In case you want to force the issue (dry run first)
    #command:  renew --http-01-port 8080 --force-renew --dry-run